apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 457472006214.dkr.ecr.us-west-1.amazonaws.com/guestbook
  newTag: d6cbdc0df33ef5f5dce803931e4d89031865223b
- name: 860967817579.dkr.ecr.us-east-2.amazonaws.com/guestbook
  newTag: 22b2c339af0647767b0b1731363b00a292b73452
- name: 860967817579.dkr.ecr.us-west-1.amazonaws.com/guestbook
  newTag: b05284a2255c0ebb206900e9d8f6bdf90c687c8f
- name: frontend
  newName: guestbook
  newTag: 3fa38b9d2acb82a6e567c5935d1037a1339e4f1d
- name: guestbook
  newName: guestbook
  newTag: new
